var ascProprias=[
{
	//basica
	img:"img/asc/basicapropria.png",
	habilidad:function(){basica(this)}
},
{
	//habilis
	img:"img/asc/habilispropria.png",
	habilidad:function(){habilis(this)}
}
]

var ascBasicas=[
{
	//basica
	img:"img/asc/basica.png",
	habilidad:function(){basica(this)}
},
{
	//chromatica
	img:"img/asc/chromatica.png",
	habilidad:function(){chromatica(this)}
},
{
	//porta
	img:"img/asc/porta.png",
	habilidad:function(){porta(this)}
},
{
	//habilis
	img:"img/asc/habilis.png",
	habilidad:function(){habilis(this)}
}
]

var ascEspeciales=[
{
	//limpida
	img:"img/asc/limpida.png",
	habilidad:function(){limpida(this)}
},
{
	//magnus
	img:"img/asc/magnus.png",
	habilidad:function(){magnus(this)}
},
{
	//mariensis
	img:"img/asc/mariensis.png",
	habilidad:function(){mariensis(this)}
},
{
	//rostellaria
	img:"img/asc/rostellaria.png",
	habilidad:function(){rostellaria(this)}
},
{
	//sverk
	img:"img/asc/sverk.png",
	habilidad:function(){sverk(this)}
},
{
	//vikenti
	img:"img/asc/vikenti.png",
	habilidad:function(){vikenti(this)}
}
]

